
package com.jk.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2017-06-30T09:14:01.589+08:00
 * Generated source version: 3.1.5
 * 
 */
public final class AreaService_AreaServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.jk.com/", "AreaServiceService");

    private AreaService_AreaServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AreaServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AreaServiceService ss = new AreaServiceService(wsdlURL, SERVICE_NAME);
        AreaService port = ss.getAreaServicePort();  
        
        {
        System.out.println("Invoking dom4JXml...");
        com.jk.service.Area _dom4JXml_arg0 = null;
        port.dom4JXml(_dom4JXml_arg0);


        }
        {
        System.out.println("Invoking findArea...");
        com.jk.service.Area _findArea_arg0 = null;
        port.findArea(_findArea_arg0);


        }

        System.exit(0);
    }

}
